### ISSUE TITLE
User can find next show for an artist.

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/ajax-project#1]
## 💰 Motivation

Users should be able to find the next show for their desired artist.

## 📐 Plan

Allow users to search for an artist's next show with TicketMaster's Discovery API.

## 🖼️ Wireframes

![user can search for artists mobile](https://user-images.githubusercontent.com/68949703/212167758-fb448125-7c87-4b8f-bc1a-1b46acf874f0.png)
![user can search for artists desktop](https://user-images.githubusercontent.com/68949703/212167695-ac3728b8-e91b-45b2-b583-18de522756c7.png)

## ✅ Task List

- [x] Create the HTML + CSS for the Navbar:
    - [x] Add a button that reads "Saved Events"
    - [x] Mobile Responsive?
    - [x] Desktop Responsive?
- [x] Create HTML form for a new event and give the container the `data-view=form` attribute and style it to match the Figma:
    - [x] Set `<img>` source (src) to placeholder image
    - [x] Mobile Responsive?
    - [x] Desktop Responsive?
- [x] Make search bar input required
- [x] Create HTML for "Event Information" section including:
    - [x] Artist
    - [x] Name
    - [x] Venue
    - [x] Address
    - [x] Date
- [x] In data.js create a data model (an object) with:
    - [x] a `view` property that will link to the `data-view` attribute, assigned to the current view `(data-view=form)`
    - [x] an `events` property assigned to an array that stores objects with the following properties (note: all **strings**):
        - [x] imageURL
       - [x] eventURL
        - [x] artist
        - [x] name
        - [x] venue
        - [x] address **(note: should follow {address, city} format)**
        - [x] date
    - [x] a `nextEventId` property assigned to 1
- [x] Add event listener to "Search" form that:
    - [x] Sends a request to the TicketMaster Discovery API with:
         - [x] A `size` query parameter of `1`
         - [x] A `sort` query parameter of `date,asc`
         - [x] A `keyword` query parameter of whatever is inside the form input
    - [x] Stores the following data (from the request) into data.js:
         - [x] `_embedded.events[0].name` (event name)
         - [x] `_embedded.events[0].url` (ticket url)
         - [x] `_embedded.events[0].dates.start.localDate` (date)
         - [x] `_embedded.events[0]._embedded.venues[0].name` (venue)
         - [x] Concatenate the following such that the returned string follows **{address, city}** format:
              - [x] `_embedded.events[0]._embedded.venues[0].address.line1` (address)
              - [x] `_embedded.events[0]._embedded.venues[0].city.name` (city)
              - [x] `_embedded.events[0]._embedded.venues[0].state.stateCode` (state)
         - [x] `_embedded.events[0].images[0].url` (image url)
         - [x] `_embedded.events[0]._embedded.attractions[0].name` (artist name)
 
    - [x] Updates the event information with the relevant data retrieved but:
         - [x] Make sure the "Event Name" is a clickable link to purchase the tickets.
    - [x] Updates the image with the 'src' set to the URL retrieved from the images sub-array
 
- [x] When "Full Send It!" button is pressed:

    - [x] Reset the form and event information
    - [x] Add the `currentEvent` object into the data model and assign it an event ID, then increment the `nextEventId` (under the `data.events` array)
    - [x] Set the image's source back to the placeholder image
    - [x] Resets `currentEvent` object back into an empty object
- [x] Add event handler to `window` that:
     - [x] Stores the data model into localStorage when the `beforeunload` event is fired
     - [x] Populates the event information and picture when `DOMContentLoaded` event is fired
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
