### ISSUE TITLE
User can save events to a list

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/ajax-project#2]
## 💰 Motivation

If a user wants to collect events they wish to go to, they should be able to make a list for it.

## 📐 Plan

Allow users to save found events into a data model that can be accessed later

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/68949703/212423752-04b25687-6750-4260-b01b-2fb8fe3433fc.png)

![image](https://user-images.githubusercontent.com/68949703/212423818-41b6b774-5a72-472d-9071-4e72a3205fc9.png)

## ✅ Task List

- [x] Create a modal that matches the formatting of the Figma using Bootstrap but:
    - [x] make sure the anchor tag is clickable and set the `href` attribute to `data.currentEvent.eventURL`
    - [x] set the anchor tag text to `data.currentEvent.name`
- [x] Add an event listener to the following that accomplishes the listed functionality:
    - [x] If YES:
        - [x] Pushes the `currentEvent` object into the `data.events` array
        - [x] Resets the `currentEvent` object
        - [x] Closes the modal on click
    - [x] If NO:
        - [x] Resets the `currentEvent` object
        - [x] Closes the modal on click
    - [x] Ensure that event information and the input properly resets when either button is clicked
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
