### ISSUE TITLE
User can view a list of saved events

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/ajax-project#3]
## 💰 Motivation

If a user created a list of saved events, they should be able to look at their list.

## 📐 Plan

Render whatever data is saved in the data model into a DOM Tree to display saved events in a different view.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/68949703/213325042-d8cd50a1-3a75-41e9-b47e-a4266452ff9c.png)

![image](https://user-images.githubusercontent.com/68949703/213325134-b390626e-6db0-4b3c-b0dd-fb6983167288.png)

## ✅ Task List

- [x] Create HTML for the "Saved Sends" view and give its container the `data-view=list` attribute and create a `ul` element inside of the container
- [x] Inside the `ul` element For the `list` view add HTML and CSS to display "No events saved!..." message
- [x] Add an event listener to the "saved events" hides the container with `data-view=form` and shows the `data-view=list` container on `click`
- [x] Create an HTML skeleton with a dummy event representing an actual saved event (use example event above)
- [x] In `main.js` create a function that gets passed an object that: 
     - [x] Make sure the "Name" is a clickable anchor tag leading to the ticket page
     - [x] takes an object matching the format of the objects in the `events` array 
     - [x] returns a DOM tree matching the dummy event
- [x] Delete the dummy event
- [x] Add an event listener to the `document` that listens for `DOMContentLoaded` that loops through the events array and renders each and appends it to the `ul` element.
- [x] Update the event listener on the confirmation button to do the following with the `currentEvent` object:
     - [x] Passes it through the render function
     - [x] Prepends the returned DOM tree to the `ul` element
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
