### ISSUE TITLE
User can create new saved events

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/ajax-project#4]
## 💰 Motivation

If a user wants to go to another event, they should be able to save that event to the list

## 📐 Plan

Utilize view-swapping to swap between the "Saved Sends" view and the "New Send" view

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/68949703/211687319-914ce698-e962-49f9-b988-d9fae34ca138.png)

![image](https://user-images.githubusercontent.com/68949703/211687330-3a33a40b-b324-4481-8ef1-2896aa9c1bd1.png)

## ✅ Task List

- [x] Add "NEW" Button on the same row as the page view header in `index.html`
- [x] Match button with styling shown in figma
- [x] Add event listener on button that listens for the `onSubmit` event that swaps view to `form` view.
- [x] Verify form submission still functions after swapping
- [x] Verify user can swap between both views   
- [x] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
