### ISSUE TITLE
User can add/view notes to events

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/ajax-project#5]
## 💰 Motivation

Users should be able to add notes to saved events if they want to form a plan

## 📐 Plan

Create a modal that pops up when the Add Notes button is clicked that saves whatever is input into the data model.
If there are notes already entered then make the text-area readonly/disabled to display them.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/68949703/211687392-3c036ded-a82b-4c0b-afa9-a45fad926b8c.png)

![image](https://user-images.githubusercontent.com/68949703/211687376-b81bb8b7-d089-40c0-9a40-89e051d5581f.png)

## ✅ Task 

- [x] Add modal dialog styled with Bootstrap that matches the one shown in the Figma
- [x] Add a form containing a save button and a text area as shown in the Figma
- [ ] Link the "Add Notes" button to the notes modal made and then add an event listener to the button that:
    - [x] If the `notes` property of that object has content then it will populate the text area with the `notes` found and the button only reads "save" when the content has changed
    - [ ] Otherwise the "save" button will instead say "close"
- [ ] Add an event listener to the save button that listens for the `submit` event and:
    - [ ] Assigns whatever is found in the text area to a new property on the corresponding object within the `events` named `notes`
    - [ ] Closes the modal dialog box
- [ ] Edit the `renderSavedEntry` function to populate the text area with whatever is stored in the `notes` property of the current event
- [ ] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
