### ISSUE TITLE
User can delete saved events

### ISSUE THREAD

**Issue by joshangeles** [joshangeles/ajax-project#6]
## 💰 Motivation

If a user changes their mind about going to an event, they should be able to remove it from their list.

## 📐 Plan

Add an "X" button on each card that, when clicked, removes that card from the list and the data model.

## 🖼️ Wireframes

![image](https://user-images.githubusercontent.com/68949703/211687441-25150f45-52b9-45ed-b2f1-86cb165b888f.png)

![image](https://user-images.githubusercontent.com/68949703/211687448-4e860c28-143d-48c0-a8c8-18d2c036bc37.png)

## ✅ Task List

- [ ] Remove all CSS styling that had no effect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
